//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/InputPlayer.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputPlayer : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputPlayer()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputPlayer"",
    ""maps"": [
        {
            ""name"": ""BarquinhoActions"",
            ""id"": ""9ca1c248-7312-4f1d-b8a2-59b4de3ae9ed"",
            ""actions"": [
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""6579e713-d80c-4cb8-b6ff-d6c879040266"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""76196533-45e3-4b8b-baed-9a0aee6bdea7"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2889d69c-ca9a-4fda-94fa-c0d85821b56c"",
                    ""path"": ""<DualShockGamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e33fe2b7-b926-45fd-b40c-3e4d2e278bdb"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // BarquinhoActions
        m_BarquinhoActions = asset.FindActionMap("BarquinhoActions", throwIfNotFound: true);
        m_BarquinhoActions_Look = m_BarquinhoActions.FindAction("Look", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // BarquinhoActions
    private readonly InputActionMap m_BarquinhoActions;
    private IBarquinhoActionsActions m_BarquinhoActionsActionsCallbackInterface;
    private readonly InputAction m_BarquinhoActions_Look;
    public struct BarquinhoActionsActions
    {
        private @InputPlayer m_Wrapper;
        public BarquinhoActionsActions(@InputPlayer wrapper) { m_Wrapper = wrapper; }
        public InputAction @Look => m_Wrapper.m_BarquinhoActions_Look;
        public InputActionMap Get() { return m_Wrapper.m_BarquinhoActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(BarquinhoActionsActions set) { return set.Get(); }
        public void SetCallbacks(IBarquinhoActionsActions instance)
        {
            if (m_Wrapper.m_BarquinhoActionsActionsCallbackInterface != null)
            {
                @Look.started -= m_Wrapper.m_BarquinhoActionsActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_BarquinhoActionsActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_BarquinhoActionsActionsCallbackInterface.OnLook;
            }
            m_Wrapper.m_BarquinhoActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
            }
        }
    }
    public BarquinhoActionsActions @BarquinhoActions => new BarquinhoActionsActions(this);
    public interface IBarquinhoActionsActions
    {
        void OnLook(InputAction.CallbackContext context);
    }
}
